export const RETRIEVE_TRADE_LOGS_SUCCESS = "RETRIEVE_TRADE_LOGS_SUCCESS";
export const RETRIEVE_TRADE_LOGS_FAILURE = "RETRIEVE_TRADE_LOGS_FAILURE";

export const RETRIEVE_PRODUCTS_START = "RETRIEVE_PRODUCTS_START";
export const RETRIEVE_PRODUCTS_SUCCESS = "RETRIEVE_PRODUCTS_SUCCESS";
export const RETRIEVE_PRODUCTS_FAILURE = "RETRIEVE_PRODUCTS_FAILURE";
